### PR TITLE
@require & @resource support

### PR DESCRIPTION
**Pull request by rbroker**
Hi,

These patches should allow you to use the @require, @resource, GM_getResourceURL and GM_getResourceText features.

- I may have taken some liberties with how much "work" I put in the "model" classes, not sure how acceptable that is from a design point of view.
- I shifted the entire download code into it's own helper class so that I could use it for require/resource downloads as well.
- I'm not sure my German translations are grammatically correct, did my best!

Cheers,
Richard

### CODE REVIEW

**Comment by rbroker** [comment]
This patch introduces a NRE in WebViewClientGm.java if script doesn't include any @require directives, needs to be changed to something like this to guard against null values:

```java
// Get @require'd scripts to inject for this script.
String jsAllRequires = "";
ScriptRequire[] requires = script.getRequires();
if (requires != null) {
for (ScriptRequire currentRequire : requires) {
    jsAllRequires += (currentRequire.getContent() + "\n");
    }
}
```

**Comment by wbayer** [comment]
Hi,

thank you very much for your contribution! Supporting @require and @resource will make the library a lot more useful.

I have reviewed your code and everything looks very good aside from a few minor things:
I'd like to keep the Script object immutable - my suggestion would be to download the require and resource content in the static parse method of Script and construct all objects with their full and final content.
Looking at the downloadRequires and downloadResources methods raises the question whether to abort all remaining downloads if one of the items cannot be retrieved (I'd let it continue).
I'd also make the new ScriptRequire and ScriptResource models immutable by removing their setters as to keep in line with the rest of the models.

Cosmetic:
Remove unused variable at line 244 in WebViewGmApi.
Remove unused import at line 26 in WebViewClientGm.
If you're using Eclipse, please run Format (Ctrl-Shift-F) and Organize Imports (Ctrl-Shift-O) on edited files.

**Comment by rbroker** [comment]
- If the download of a resource or require fails that leaves the script in an indeterminate state of "completeness". I'm not sure we should continue on failure for that reason - Greasemonkey fails in this case.
- I was initially downloading the requires/resources in ScriptBrowser so that I could give a more appropriate error message when the download failed, but I suppose most users wouldn't care why the installation failed, only that it did - because they couldn't fix it themselves either way.
- I'll move the XmlHttpRequest and XmlHttpResponse classes to the "run" namespace because they're mutable.
- I'm using Android Studio which is the IntelliJ-based IDE, so I'm not sure if those commands would be equivalent to the eclipse versions in terms of style, so it might be best if you executed those after the merge to your branch and them committed a style update in your environment.

**Comment by wbayer** [comment]
Thanks for checking how Greasemonkey does it - that's definitely the way to go then.
Great work on the GM_xmlhttpRequest implementation! I have looked through the code and tested it, and everything is working nicely. I have only noticed one thing that might become an issue in future versions of Android: the loadUrl calls in the WebViewXmlHttpRequest class are not necessarily executed on the UI thread. I have had a similar problem in the Pardus app in PardusMessageChecker and solved it by using a handler on the UI thread to post Runnables to.

**Pull request merged**
